import {ArrowType} from "../api/arrowType";

export const ACTIVE_SIGNALS: Array<number> = new Array<number>(25);
ACTIVE_SIGNALS[ArrowType.EMPTY] = -1
ACTIVE_SIGNALS[ArrowType.ARROW] = 1
ACTIVE_SIGNALS[ArrowType.SOURCE] = 1
ACTIVE_SIGNALS[ArrowType.BLOCKER] = 1
ACTIVE_SIGNALS[ArrowType.DELAY] = 1
ACTIVE_SIGNALS[ArrowType.DETECTOR] = 1
ACTIVE_SIGNALS[ArrowType.SPLITTER_UP_DOWN] = 1
ACTIVE_SIGNALS[ArrowType.SPLITTER_UP_RIGHT] = 1
ACTIVE_SIGNALS[ArrowType.SPLITTER_UP_RIGHT_LEFT] = 1
ACTIVE_SIGNALS[ArrowType.IMPULSE] = 1
ACTIVE_SIGNALS[ArrowType.BLUE_ARROW] = 2
ACTIVE_SIGNALS[ArrowType.DIAGONAL_ARROW] = 2
ACTIVE_SIGNALS[ArrowType.SPLITTER_UP_UP] = 2
ACTIVE_SIGNALS[ArrowType.SPLITTER_RIGHT_UP] = 2
ACTIVE_SIGNALS[ArrowType.SPLITTER_UP_DIAGONAL] = 2
ACTIVE_SIGNALS[ArrowType.LOGIC_NOT] = 3
ACTIVE_SIGNALS[ArrowType.LOGIC_AND] = 3
ACTIVE_SIGNALS[ArrowType.LOGIC_XOR] = 3
ACTIVE_SIGNALS[ArrowType.LATCH] = 3
ACTIVE_SIGNALS[ArrowType.FLIP_FLOP] = 3
ACTIVE_SIGNALS[ArrowType.RANDOM] = 5
ACTIVE_SIGNALS[ArrowType.BUTTON] = 5
ACTIVE_SIGNALS[ArrowType.LEVEL_SOURCE] = 1
ACTIVE_SIGNALS[ArrowType.LEVEL_TARGET] = 1
ACTIVE_SIGNALS[ArrowType.DIRECTIONAL_BUTTON] = 5
